CFLAGS_bsc1217116_drivers_gpu_drm_qxl_qxl_dumb.o += -Werror
CFLAGS_bsc1217116/bsc1217116_drivers_gpu_drm_qxl_qxl_dumb.o += -Werror
CFLAGS_bsc1217116_drivers_gpu_drm_qxl_qxl_gem.o += -Werror
CFLAGS_bsc1217116/bsc1217116_drivers_gpu_drm_qxl_qxl_gem.o += -Werror
CFLAGS_bsc1217116_drivers_gpu_drm_qxl_qxl_ioctl.o += -Werror
CFLAGS_bsc1217116/bsc1217116_drivers_gpu_drm_qxl_qxl_ioctl.o += -Werror
CFLAGS_livepatch_bsc1217116.o += -Werror
CFLAGS_bsc1217116/livepatch_bsc1217116.o += -Werror
