CFLAGS_bsc1213584_net_netfilter_nf_tables_api.o += -Werror
CFLAGS_bsc1213584/bsc1213584_net_netfilter_nf_tables_api.o += -Werror
CFLAGS_bsc1213584_net_netfilter_nft_immediate.o += -Werror
CFLAGS_bsc1213584/bsc1213584_net_netfilter_nft_immediate.o += -Werror
CFLAGS_livepatch_bsc1213584.o += -Werror
CFLAGS_bsc1213584/livepatch_bsc1213584.o += -Werror
