CFLAGS_bsc1265224_net_core_gro.o += -Werror
CFLAGS_bsc1265224/bsc1265224_net_core_gro.o += -Werror
CFLAGS_bsc1265224_net_core_skbuff.o += -Werror
CFLAGS_bsc1265224/bsc1265224_net_core_skbuff.o += -Werror
