CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_bo.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_execbuf.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_gem.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_kms.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_overlay.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_shader.o += -Werror
CFLAGS_bsc1212348/bsc1212348_drivers_gpu_drm_vmwgfx_vmwgfx_surface.o += -Werror
CFLAGS_bsc1212348/livepatch_bsc1212348.o += -Werror
