CFLAGS_bsc1253437_net_sctp_sm_make_chunk.o += -Werror
CFLAGS_bsc1253437/bsc1253437_net_sctp_sm_make_chunk.o += -Werror
CFLAGS_bsc1253437_net_sctp_sm_statefuns.o += -Werror
CFLAGS_bsc1253437/bsc1253437_net_sctp_sm_statefuns.o += -Werror
