CFLAGS_bsc1231993_net_ipv4_tcp_input.o += -Werror
CFLAGS_bsc1231993/bsc1231993_net_ipv4_tcp_input.o += -Werror
CFLAGS_bsc1231993_net_ipv4_tcp_output.o += -Werror
CFLAGS_bsc1231993/bsc1231993_net_ipv4_tcp_output.o += -Werror
CFLAGS_livepatch_bsc1231993.o += -Werror
CFLAGS_bsc1231993/livepatch_bsc1231993.o += -Werror
