CFLAGS_bsc1211395_net_ipv6_rpl.o += -Werror
CFLAGS_bsc1211395/bsc1211395_net_ipv6_rpl.o += -Werror
CFLAGS_bsc1211395_net_ipv6_exthdrs.o += -Werror
CFLAGS_bsc1211395/bsc1211395_net_ipv6_exthdrs.o += -Werror
CFLAGS_livepatch_bsc1211395.o += -Werror
CFLAGS_bsc1211395/livepatch_bsc1211395.o += -Werror
