CFLAGS_bsc1264459_net_ipv6_ip6_output.o += -Werror
CFLAGS_bsc1264459/bsc1264459_net_ipv6_ip6_output.o += -Werror
CFLAGS_bsc1264459_net_ipv4_ip_output.o += -Werror
CFLAGS_bsc1264459/bsc1264459_net_ipv4_ip_output.o += -Werror
CFLAGS_bsc1264459_net_ipv4_esp4.o += -Werror
CFLAGS_bsc1264459/bsc1264459_net_ipv4_esp4.o += -Werror
CFLAGS_bsc1264459_net_ipv6_esp6.o += -Werror
CFLAGS_bsc1264459/bsc1264459_net_ipv6_esp6.o += -Werror
