CFLAGS_REMOVE_bsc1207822_net_core_rtnetlink.o += -Werror
CFLAGS_bsc1207822_net_sched_cls_api.o += -Werror
CFLAGS_bsc1207822_net_sched_sch_api.o += -Werror
CFLAGS_bsc1207822_net_sched_sch_generic.o += -Werror
CFLAGS_livepatch_bsc1207822.o += -Werror
