CFLAGS_bsc1247158_mm_secretmem.o += -Werror
CFLAGS_bsc1247158/bsc1247158_mm_secretmem.o += -Werror
CFLAGS_bsc1247158_fs_anon_inodes.o += -Werror
CFLAGS_bsc1247158/bsc1247158_fs_anon_inodes.o += -Werror
CFLAGS_livepatch_bsc1247158.o += -Werror
CFLAGS_bsc1247158/livepatch_bsc1247158.o += -Werror
