CFLAGS_bsc1243650_net_sunrpc_svcsock.o += -Werror
CFLAGS_bsc1243650/bsc1243650_net_sunrpc_svcsock.o += -Werror
CFLAGS_bsc1243650_net_sunrpc_xprtsock.o += -Werror
CFLAGS_bsc1243650/bsc1243650_net_sunrpc_xprtsock.o += -Werror
CFLAGS_livepatch_bsc1243650.o += -Werror
CFLAGS_bsc1243650/livepatch_bsc1243650.o += -Werror
