CFLAGS_bsc1249537_net_tls_tls_strp.o += -Werror
CFLAGS_bsc1249537/bsc1249537_net_tls_tls_strp.o += -Werror
CFLAGS_bsc1249537_net_tls_tls_sw.o += -Werror
CFLAGS_bsc1249537/bsc1249537_net_tls_tls_sw.o += -Werror
