CFLAGS_bsc1229640_net_netfilter_nf_queue.o += -Werror
CFLAGS_bsc1229640/bsc1229640_net_netfilter_nf_queue.o += -Werror
CFLAGS_bsc1229640_net_netfilter_nfnetlink_queue.o += -Werror
CFLAGS_bsc1229640/bsc1229640_net_netfilter_nfnetlink_queue.o += -Werror
CFLAGS_livepatch_bsc1229640.o += -Werror
CFLAGS_bsc1229640/livepatch_bsc1229640.o += -Werror
