CFLAGS_bsc1226327_kernel_bpf_verifier.o += -Werror
CFLAGS_bsc1226327/bsc1226327_kernel_bpf_verifier.o += -Werror
CFLAGS_bsc1226327_kernel_bpf_syscall.o += -Werror
CFLAGS_bsc1226327/bsc1226327_kernel_bpf_syscall.o += -Werror
CFLAGS_livepatch_bsc1226327.o += -Werror
CFLAGS_bsc1226327/livepatch_bsc1226327.o += -Werror
