CFLAGS_bsc1216644_kernel_events_core.o += -Werror
CFLAGS_bsc1216644/bsc1216644_kernel_events_core.o += -Werror
CFLAGS_bsc1216644_fs_read_write.o += -Werror
CFLAGS_bsc1216644/bsc1216644_fs_read_write.o += -Werror
CFLAGS_bsc1216644_fs_io_uring.o += -Werror
CFLAGS_bsc1216644/bsc1216644_fs_io_uring.o += -Werror
CFLAGS_livepatch_bsc1216644.o += -Werror
CFLAGS_bsc1216644/livepatch_bsc1216644.o += -Werror
