CFLAGS_bsc1215887_kernel_bpf_verifier.o += -Werror
CFLAGS_bsc1215887/bsc1215887_kernel_bpf_verifier.o += -Werror
CFLAGS_bsc1215887_kernel_bpf_helpers.o += -Werror
CFLAGS_bsc1215887/bsc1215887_kernel_bpf_helpers.o += -Werror
CFLAGS_livepatch_bsc1215887.o += -Werror
CFLAGS_bsc1215887/livepatch_bsc1215887.o += -Werror
