CFLAGS_bsc1242579_fs_proc_inode.o += -Werror
CFLAGS_bsc1242579/bsc1242579_fs_proc_inode.o += -Werror
CFLAGS_bsc1242579_fs_proc_generic.o += -Werror
CFLAGS_bsc1242579/bsc1242579_fs_proc_generic.o += -Werror
CFLAGS_livepatch_bsc1242579.o += -Werror
CFLAGS_bsc1242579/livepatch_bsc1242579.o += -Werror
