CFLAGS_bsc1249241_net_ipv6_ip6_fib.o += -Werror
CFLAGS_bsc1249241/bsc1249241_net_ipv6_ip6_fib.o += -Werror
CFLAGS_bsc1249241_net_ipv6_route.o += -Werror
CFLAGS_bsc1249241/bsc1249241_net_ipv6_route.o += -Werror
