CFLAGS_bsc1258655_net_ipv4_route.o += -Werror
CFLAGS_bsc1258655/bsc1258655_net_ipv4_route.o += -Werror
CFLAGS_bsc1258655_net_ipv6_route.o += -Werror
CFLAGS_bsc1258655/bsc1258655_net_ipv6_route.o += -Werror
