CFLAGS_bsc1267388_fs_notify_fsnotify.o += -Werror
CFLAGS_bsc1267388/bsc1267388_fs_notify_fsnotify.o += -Werror
CFLAGS_bsc1267388_fs_notify_mark.o += -Werror
CFLAGS_bsc1267388/bsc1267388_fs_notify_mark.o += -Werror
CFLAGS_livepatch_bsc1267388.o += -Werror
CFLAGS_bsc1267388/livepatch_bsc1267388.o += -Werror
