CFLAGS_bsc1227656_net_tls_tls_sw.o += -Werror
CFLAGS_bsc1227656/bsc1227656_net_tls_tls_sw.o += -Werror
CFLAGS_bsc1227656_net_tls_tls_device.o += -Werror
CFLAGS_bsc1227656/bsc1227656_net_tls_tls_device.o += -Werror
CFLAGS_livepatch_bsc1227656.o += -Werror
CFLAGS_bsc1227656/livepatch_bsc1227656.o += -Werror
