CFLAGS_bsc1255402_net_ceph_debugfs.o += -Werror
CFLAGS_bsc1255402/bsc1255402_net_ceph_debugfs.o += -Werror
CFLAGS_bsc1255402_net_ceph_ceph_common.o += -Werror
CFLAGS_bsc1255402/bsc1255402_net_ceph_ceph_common.o += -Werror
CFLAGS_livepatch_bsc1255402.o += -Werror
CFLAGS_bsc1255402/livepatch_bsc1255402.o += -Werror
