CFLAGS_bsc1229275_fs_cachefiles_volume.o += -Werror
CFLAGS_bsc1229275/bsc1229275_fs_cachefiles_volume.o += -Werror
CFLAGS_bsc1229275_fs_fscache_volume.o += -Werror
CFLAGS_bsc1229275/bsc1229275_fs_fscache_volume.o += -Werror
CFLAGS_bsc1229275_fs_cachefiles_cache.o += -Werror
CFLAGS_bsc1229275/bsc1229275_fs_cachefiles_cache.o += -Werror
CFLAGS_livepatch_bsc1229275.o += -Werror
CFLAGS_bsc1229275/livepatch_bsc1229275.o += -Werror
