CFLAGS_bsc1263689_crypto_algif_aead.o += -Werror
CFLAGS_bsc1263689/bsc1263689_crypto_algif_aead.o += -Werror
CFLAGS_bsc1263689_crypto_authencesn.o += -Werror
CFLAGS_bsc1263689/bsc1263689_crypto_authencesn.o += -Werror
CFLAGS_livepatch_bsc1263689.o += -Werror
CFLAGS_bsc1263689/livepatch_bsc1263689.o += -Werror
