CFLAGS_livepatch_bsc1270023.o += -Werror
CFLAGS_bsc1270023/livepatch_bsc1270023.o += -Werror
CFLAGS_bsc1270023_net_sctp_bind_addr.o += -Werror
CFLAGS_bsc1270023/bsc1270023_net_sctp_bind_addr.o += -Werror
CFLAGS_bsc1270023_net_sctp_sm_make_chunk.o += -Werror
CFLAGS_bsc1270023/bsc1270023_net_sctp_sm_make_chunk.o += -Werror
