CFLAGS_bsc1218259_kernel_events_core.o += -Werror
CFLAGS_bscbsc1218259/bsc1218259_kernel_events_core.o += -Werror
CFLAGS_bsc1218259_fs_read_write.o += -Werror
CFLAGS_bscbsc1218259/bsc1218259_fs_read_write.o += -Werror
CFLAGS_livepatch_bsc1218259.o += -Werror
CFLAGS_bscbsc1218259/livepatch_bsc1218259.o += -Werror
