CFLAGS_bsc1233678_net_ipv4_ip_tunnel.o += -Werror
CFLAGS_bsc1233678/bsc1233678_net_ipv4_ip_tunnel.o += -Werror
CFLAGS_bsc1233678_net_ipv4_ip_gre.o += -Werror
CFLAGS_bsc1233678/bsc1233678_net_ipv4_ip_gre.o += -Werror
CFLAGS_bsc1233678_drivers_net_ethernet_mellanox_mlxsw_spectrum_span.o += -Werror
CFLAGS_bsc1233678/bsc1233678_drivers_net_ethernet_mellanox_mlxsw_spectrum_span.o += -Werror
CFLAGS_livepatch_bsc1233678.o += -Werror
CFLAGS_bsc1233678/livepatch_bsc1233678.o += -Werror
